// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.3.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides in ThisBuild ++= Set(

)
// LIBRARY_DEPENDENCIES_HASH 6d51f29b9a8f4bced0090f2a51d085f21925c0d5
