// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.3.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides in ThisBuild ++= Set(
  "com.chuusai" % "shapeless_sjs0.6_2.12" % "2.3.2",
  "com.github.mpilquist" % "simulacrum_sjs0.6_2.12" % "0.10.0",
  "com.lihaoyi" % "scalatags_sjs0.6_2.12" % "0.6.5",
  "com.lihaoyi" % "sourcecode_sjs0.6_2.12" % "0.1.3",
  "io.circe" % "circe-core_sjs0.6_2.12" % "0.8.0",
  "io.circe" % "circe-generic_sjs0.6_2.12" % "0.8.0",
  "io.circe" % "circe-numbers_sjs0.6_2.12" % "0.8.0",
  "io.circe" % "circe-parser_sjs0.6_2.12" % "0.8.0",
  "io.circe" % "circe-scalajs_sjs0.6_2.12" % "0.8.0",
  "org.scala-js" % "scalajs-dom_sjs0.6_2.12" % "0.9.1",
  "org.scala-js" % "scalajs-library_2.12" % "0.6.17",
  "org.typelevel" % "cats-core_sjs0.6_2.12" % "0.9.0",
  "org.typelevel" % "cats-kernel_sjs0.6_2.12" % "0.9.0",
  "org.typelevel" % "cats-macros_sjs0.6_2.12" % "0.9.0",
  "org.typelevel" % "machinist_sjs0.6_2.12" % "0.6.1",
  "org.typelevel" % "macro-compat_2.12" % "1.1.1",
  "org.typelevel" % "macro-compat_sjs0.6_2.12" % "1.1.1"
)
// LIBRARY_DEPENDENCIES_HASH 55e12f6b9f65bf22cbf0f7aed375ef7e9bdd0845
